"""Add new fields for Customer and ServiceProfessional

Revision ID: 3e5110c2030b
Revises: 
Create Date: 2024-10-02 16:33:58.702962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5110c2030b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=False))

    with op.batch_alter_table('service_professional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('pincode', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('documents', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_professional', schema=None) as batch_op:
        batch_op.drop_column('documents')
        batch_op.drop_column('pincode')
        batch_op.drop_column('address')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('pincode')

    # ### end Alembic commands ###
