"""Added in Services

Revision ID: 8a1531175bfb
Revises: 11345e16e4f7
Create Date: 2024-10-13 12:28:03.410483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1531175bfb'
down_revision = '11345e16e4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_professional', schema=None) as batch_op:
        batch_op.alter_column('service_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_service_professional_service', 'service', ['service_type'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_professional', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_professional_service', type_='foreignkey')
        batch_op.alter_column('service_type',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
